language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly

before_script:
    - composer self-update
    - composer require phpspec/phpspec:~2.0 --no-update
    - composer install --dev --prefer-dist --no-interaction

script:
    - ./vendor/bin/phpspec run -fpretty
